server:
  port: 3344

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jy-chen-xy/usian-config.git #GitHub上面的git仓库名字
  rabbitmq:
    host: 192.168.2.101
    username: admin
    password: 1111
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh #springboot 默认开启了权限拦截 会导致/bus-refresh出现 405，拒绝访问